#ifndef DASHTUP_CONFIG_H
#define DASHTUP_CONFIG_H

#define DASHTUP_VERSION "1.4.0"
#define DASH_PACKAGE_VERSION "5.0.0LL"
#define DASH_DOC_VERSION "v3.1.0"

#define DASHTUP_ENV_PREFIX "DASHTUP_PREFIX"
#define DASHTUP_ENV_HOME "DASHTUP_HOME"
#define DASHTUP_ENV_ASSUME_YES "DASHTUP_ASSUME_YES"

#define DASHTUP_STATE_FILE ".dashtup-state"
#define DASHTUP_BACKUP_NAME "dash.dashtup.backup"

#endif
